version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: ozon:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user_db:1234@db:5433/ozon?sslmode=disable

  db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user_db        
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: ozon            
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
  test:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: builder  # Используем стадию builder, где установлен Go
    command: go test ./... -v
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user_db:1234@db:5433/ozon?sslmode=disable
      
volumes:
  db_data:

networks:
  app-network:
