// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	Text     string     `json:"text"`
	PostID   string     `json:"postId"`
	ParentID *string    `json:"parentId,omitempty"`
	Children []*Comment `json:"children"`
	Author   *User      `json:"author"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Comments      []*Comment `json:"comments"`
	AllowComments bool       `json:"allowComments"`
	Author        *User      `json:"author"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID string `json:"id"`
}
